var slbh = "KFQ201703150027-1"
var data = {
  "djcf":"select SLBH,XGZH,BDCDYH,CFJG,CFLX,CFWJ,CFWH,CFQSSJ,CFJSSJ,CFFW,DJJG,DBR,DJSJ,CFYY,JBR,QLR,YGR,ZJBH,LHXX,JBRQ,GDH,DAMJ,QT,FJ,LIFECYCLE,LWRQ,CFBH,CFSX,CFQX from DJ_CF where SLBH LIKE " + "'" + slbh + "%'",
  "ggcflx":"select ITEMVAL,ITEMNAME from DIC_ITEM where dicCode in (SELECT DICCODE FROM dic_main WHERE DICNAME = '查封类型') order by ITEMVAL",
  "djsjd":"select SLBH, LCLX, LCMC, SJR, SJSJ, CNSJ, QXDM, TZRXM, TZFS, TZRDH, TZRYDDH, TZRDZYJ, TZRTXDZ, CXMM, SJMC, SJLX, SJSL, YS, SFSYBZ, SFEWSJ, SFBCSJ, ZRKS, ZRR, YXJ, SJBZ, BCSM,ZL from DJ_SJD where SLBH LIKE " + "'" + slbh + "%'",
  "djtsgl":"select GLBM, SLBH, BDCLX, TSTYBM, BDCDYH, DJZL, GLMS, CSSJ from DJ_TSGL where SLBH LIKE " + "'" + slbh + "%'",
  "ggssxq":"select ITEMNOTE,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '所属辖区' AND ROWNUM<2) ORDER BY ITEMORDER",
  "ggtzfs":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '通知方式' AND ROWNUM<2) ORDER BY ITEMORDER",
  "ggzrks":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '责任科室' AND ROWNUM<2) ORDER BY ITEMORDER",
  "ggzrr":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '责任人' AND ROWNUM<2) ORDER BY ITEMORDER",
  "ggyxj":"select ITEMVAL, ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '优先级' AND ROWNUM<2) ORDER BY ITEMORDER",
  "ggsjlx":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '收件类型' AND ROWNUM<2) ORDER BY ITEMORDER",
  "ggsf":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '是否' AND ROWNUM<2) ORDER BY ITEMORDER",
  "ggdjlx":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '登记类型(大类)' AND ROWNUM<2) ORDER BY ITEMORDER",
}
