const { dateEquals } = require("element-plus")

var slbh = "KFQ202209160023";
var data = {
     "djsjd":"select SLBH,QXKZ,LCLX, LCMC, SJR, SJSJ, CNSJ, QXDM, TZRXM, TZFS, TZRDH, TZRYDDH, TZRDZYJ, TZRTXDZ, CXMM, SJMC, SJLX, SJSL, YS, SFSYBZ, SFEWSJ, SFBCSJ, ZRKS,ZRR,YXJ,SJBZ,BCSM,DJXL,FCSLH,FCDJLX,JYBH,FCHID,DJDL,ZL,HTBH,PCH,PRJID,XCZP,LCLB from DJ_SJD where SLBH = 'KFQ202209160023'",
     "djdjb":"select SLBH,SQFBCZ,GYFS,DJLX,DJYY,DJRQ,SQRQ,XGZH,LIFECYCLE from DJ_DJB where SLBH = 'KFQ202209160023'",
     "djtsgl":"select LIFECYCLE from DJ_TSGL where SLBH = 'KFQ202209160023'",
     "ggdjyy":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '房屋转移登记原因' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggzrks":"select ITEMNOTE AS ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '责任科室' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggsjr":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '收件人' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggyxj":"select ITEMVAL, ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '优先级' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggssxq":"select ITEMNOTE,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '所属辖区' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggtzfs":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '通知方式' AND ROWNUM<2) ORDER BY ITEMORDER",
     "gggyfs":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE =(SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '共有方式' AND ROWNUM < 2 ) ORDER BY ITEMORDER",
     "ggdjxl":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '国有建设用地使用权及房屋所有权转移登记' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggdjlx":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '登记类型(大类)' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggzjlx":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '证件类型' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggsjbz2":"select ITEMVAL,ITEMNAME from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '收件备注' AND ROWNUM<2) AND ITEMNOTE IS NOT NULL ORDER BY ITEMORDER",
     "ggqygpy":"select ITEMVAL from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '设备' AND ROWNUM < 2) AND ITEMNAME = '现场拍照启用高拍仪' AND ROWNUM < 2",
     "ggdjxlms":"select ITEMNOTE,ITEMVAL from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '国有建设用地使用权及房屋所有权转移登记' AND ROWNUM<2) ORDER BY ITEMORDER",
     "ggxsqx":"select ITEMVAL from DIC_ITEM where DICCODE = (SELECT DICCODE FROM DIC_MAIN WHERE DICNAME = '限购限售控制' AND ROWNUM < 2) AND ITEMNAME = '限售' AND ROWNUM < 2",
     "gglclb":"select ItemVal,ItemName from DIC_ITEM where dicCode =(SELECT DICCODE FROM dic_main WHERE DICNAME = '流程类别' And RowNum<2)"
     }
